# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run my script with the secret
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run: |
        
        bot_token="$BOT_TOKEN"
        
        cat $bot_token
        
        sed -i 's/^token=.*/token=$bot_token/' utils/settings.ini
        
        cat utils/settings.ini

    - name: Setup Bot.py
      run: |
        # run the bot on dedicate server
                
        python Bot.py
